//! End-to-end protobuf test: reads binary payloads generated by
//! the official Go protobuf library and validates deserialization.
const std = @import("std");
const protobuf = @import("comptime_serde").protobuf;

const Server = struct { host: []const u8, port: u32 };

const SignedMsg = struct {
    value: i32,
    pub const serde_fields = .{
        .value = .{ .protobuf = .{ .zigzag = true } },
    };
};

const cases = .{
    .{
        "simple.bin",
        struct { name: []const u8, port: u32, flag: bool },
        .{ .name = "hello", .port = 8080, .flag = true },
    },
    .{
        "nested.bin",
        struct { name: []const u8, server: Server },
        .{ .name = "myapp", .server = .{ .host = "localhost", .port = 8080 } },
    },
    .{
        "packed.bin",
        struct { scores: []const u32 },
        .{ .scores = &[_]u32{ 100, 200, 300 } },
    },
    .{
        "repeated.bin",
        struct { servers: []const Server },
        .{ .servers = &[_]Server{
            .{ .host = "a.com", .port = 80 },
            .{ .host = "b.com", .port = 443 },
        } },
    },
    .{
        "enum.bin",
        struct { status: enum(u32) { active = 0, inactive = 1 } },
        .{ .status = .inactive },
    },
    .{
        "signed.bin",
        SignedMsg,
        .{ .value = -42 },
    },
    .{
        "float.bin",
        struct { f: f32, d: f64 },
        .{ .f = 3.14, .d = 2.71828 },
    },
    .{
        "optional_string.bin",
        struct { name: []const u8, tag: ?[]const u8 = null },
        .{ .name = "test", .tag = "hello" },
    },
    .{
        "optional_struct.bin",
        struct { name: []const u8, server: ?Server = null },
        .{ .name = "app", .server = .{ .host = "localhost", .port = 8080 } },
    },
};

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;
    const dir = std.Io.Dir.cwd().openDir(io, "tests/payloads", .{}) catch
        std.process.fatal("cannot open tests/payloads", .{});

    // Phase 1: Read Go-generated payloads and verify Zig deserialization.
    inline for (cases) |entry| {
        const name = entry[0];
        const T = entry[1];
        const expected = entry[2];
        const payload = dir.readFileAlloc(io, name, allocator, .limited(4096)) catch
            std.process.fatal("cannot read {s}", .{name});
        defer allocator.free(payload);
        var result = try protobuf.Serde(T).deserialize(allocator, payload);
        defer result.deinit();
        try expectEqual(expected, result.value);
    }

    // Phase 2: Serialize structs and write .bin files for Go to verify.
    const cwd = std.Io.Dir.cwd();
    cwd.createDirPath(io, "tests/zig-output") catch
        std.process.fatal("cannot create tests/zig-output", .{});
    const out_dir = cwd.openDir(io, "tests/zig-output", .{}) catch
        std.process.fatal("cannot open tests/zig-output", .{});

    inline for (cases) |entry| {
        const name = entry[0];
        const T = entry[1];
        var buf: [4096]u8 = undefined;
        var writer = std.Io.Writer.fixed(&buf);
        const value = initValue(T, entry[2]);
        protobuf.Serde(T).serialize(&writer, allocator, value) catch
            std.process.fatal("cannot serialize {s}", .{name});
        out_dir.writeFile(io, .{
            .sub_path = name,
            .data = writer.buffered(),
        }) catch
            std.process.fatal("cannot write {s}", .{name});
    }

    std.debug.print("All 9 pb-e2e tests passed.\n", .{});
}

/// Converts an anonymous struct literal to the target type T.
fn initValue(comptime T: type, comptime source: anytype) T {
    const info = @typeInfo(T);
    if (info != .@"struct") return source;
    var result: T = undefined;
    inline for (info.@"struct".fields) |field| {
        const src_val = @field(source, field.name);
        const field_info = @typeInfo(field.type);
        if (field_info == .@"struct") {
            @field(result, field.name) = initValue(field.type, src_val);
        } else if (field_info == .optional) {
            const child = field_info.optional.child;
            if (@typeInfo(child) == .@"struct") {
                @field(result, field.name) = initValue(child, src_val);
            } else {
                @field(result, field.name) = src_val;
            }
        } else {
            @field(result, field.name) = src_val;
        }
    }
    return result;
}

/// Recursively compares struct fields between expected and actual values.
fn expectEqual(expected: anytype, actual: anytype) !void {
    const E = @TypeOf(expected);
    inline for (@typeInfo(E).@"struct".fields) |field| {
        const exp = @field(expected, field.name);
        const act = @field(actual, field.name);
        try expectFieldEqual(exp, act);
    }
}

/// Dispatches comparison based on the actual value's type.
fn expectFieldEqual(expected: anytype, actual: anytype) !void {
    const E = @TypeOf(expected);
    const A = @TypeOf(actual);
    const e_info = @typeInfo(E);
    const a_info = @typeInfo(A);

    if (E == []const u8 or A == []const u8) {
        try std.testing.expectEqualStrings(expected, actual);
    } else if (a_info == .optional) {
        if (actual) |act| {
            try expectFieldEqual(expected, act);
        } else {
            return error.TestExpectedEqual;
        }
    } else if (a_info == .pointer and a_info.pointer.size == .slice) {
        try std.testing.expectEqual(expected.len, actual.len);
        for (expected, actual) |e, a| try expectFieldEqual(e, a);
    } else if (e_info == .@"struct" and a_info == .@"struct") {
        try expectEqual(expected, actual);
    } else if (a_info == .float) {
        try std.testing.expectApproxEqAbs(@as(A, expected), actual, 0.001);
    } else {
        try std.testing.expectEqual(expected, actual);
    }
}
