// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: testdata.proto

package tests

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Matches Zig: enum(u32) { active = 0, inactive = 1 }
type Status int32

const (
	Status_active   Status = 0
	Status_inactive Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "active",
		1: "inactive",
	}
	Status_value = map[string]int32{
		"active":   0,
		"inactive": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_testdata_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{0}
}

// Matches Zig: struct { name: []const u8, port: u32, flag: bool }
type SimpleMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Flag          bool                   `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleMessage) Reset() {
	*x = SimpleMessage{}
	mi := &file_testdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessage) ProtoMessage() {}

func (x *SimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMessage.ProtoReflect.Descriptor instead.
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimpleMessage) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SimpleMessage) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

// Matches Zig: struct { host: []const u8, port: u32 }
type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_testdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Server) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Matches Zig: struct { name: []const u8, server: Server }
type NestedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Server        *Server                `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedMessage) Reset() {
	*x = NestedMessage{}
	mi := &file_testdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMessage) ProtoMessage() {}

func (x *NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMessage.ProtoReflect.Descriptor instead.
func (*NestedMessage) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{2}
}

func (x *NestedMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NestedMessage) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

// Matches Zig: struct { scores: []const u32 }
type PackedScalars struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []uint32               `protobuf:"varint,1,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackedScalars) Reset() {
	*x = PackedScalars{}
	mi := &file_testdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackedScalars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackedScalars) ProtoMessage() {}

func (x *PackedScalars) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackedScalars.ProtoReflect.Descriptor instead.
func (*PackedScalars) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{3}
}

func (x *PackedScalars) GetScores() []uint32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

// Matches Zig: struct { servers: []const Server }
type RepeatedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*Server              `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedMessage) Reset() {
	*x = RepeatedMessage{}
	mi := &file_testdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedMessage) ProtoMessage() {}

func (x *RepeatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedMessage.ProtoReflect.Descriptor instead.
func (*RepeatedMessage) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{4}
}

func (x *RepeatedMessage) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

// Matches Zig: struct { status: Status }
type EnumMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=testdata.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumMessage) Reset() {
	*x = EnumMessage{}
	mi := &file_testdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumMessage) ProtoMessage() {}

func (x *EnumMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumMessage.ProtoReflect.Descriptor instead.
func (*EnumMessage) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{5}
}

func (x *EnumMessage) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_active
}

// Zig signed ints use ZigZag encoding, so use sint32/sint64.
// Matches Zig: struct { value: i32 }
type SignedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"zigzag32,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedMessage) Reset() {
	*x = SignedMessage{}
	mi := &file_testdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedMessage) ProtoMessage() {}

func (x *SignedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedMessage.ProtoReflect.Descriptor instead.
func (*SignedMessage) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{6}
}

func (x *SignedMessage) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Matches Zig: struct { f: f32, d: f64 }
type FloatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	F             float32                `protobuf:"fixed32,1,opt,name=f,proto3" json:"f,omitempty"`
	D             float64                `protobuf:"fixed64,2,opt,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatMessage) Reset() {
	*x = FloatMessage{}
	mi := &file_testdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatMessage) ProtoMessage() {}

func (x *FloatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatMessage.ProtoReflect.Descriptor instead.
func (*FloatMessage) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{7}
}

func (x *FloatMessage) GetF() float32 {
	if x != nil {
		return x.F
	}
	return 0
}

func (x *FloatMessage) GetD() float64 {
	if x != nil {
		return x.D
	}
	return 0
}

// Matches Zig: struct { name: []const u8, tag: ?[]const u8 = null }
type OptionalStringMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag           *string                `protobuf:"bytes,2,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalStringMessage) Reset() {
	*x = OptionalStringMessage{}
	mi := &file_testdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalStringMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalStringMessage) ProtoMessage() {}

func (x *OptionalStringMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalStringMessage.ProtoReflect.Descriptor instead.
func (*OptionalStringMessage) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{8}
}

func (x *OptionalStringMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OptionalStringMessage) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

// Matches Zig: struct { name: []const u8, server: ?Server = null }
type OptionalStructMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Server        *Server                `protobuf:"bytes,2,opt,name=server,proto3,oneof" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalStructMessage) Reset() {
	*x = OptionalStructMessage{}
	mi := &file_testdata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalStructMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalStructMessage) ProtoMessage() {}

func (x *OptionalStructMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalStructMessage.ProtoReflect.Descriptor instead.
func (*OptionalStructMessage) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{9}
}

func (x *OptionalStructMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OptionalStructMessage) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

var File_testdata_proto protoreflect.FileDescriptor

const file_testdata_proto_rawDesc = "" +
	"\n" +
	"\x0etestdata.proto\x12\btestdata\"K\n" +
	"\rSimpleMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x12\n" +
	"\x04flag\x18\x03 \x01(\bR\x04flag\"0\n" +
	"\x06Server\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"M\n" +
	"\rNestedMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x06server\x18\x02 \x01(\v2\x10.testdata.ServerR\x06server\"'\n" +
	"\rPackedScalars\x12\x16\n" +
	"\x06scores\x18\x01 \x03(\rR\x06scores\"=\n" +
	"\x0fRepeatedMessage\x12*\n" +
	"\aservers\x18\x01 \x03(\v2\x10.testdata.ServerR\aservers\"7\n" +
	"\vEnumMessage\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.testdata.StatusR\x06status\"%\n" +
	"\rSignedMessage\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x11R\x05value\"*\n" +
	"\fFloatMessage\x12\f\n" +
	"\x01f\x18\x01 \x01(\x02R\x01f\x12\f\n" +
	"\x01d\x18\x02 \x01(\x01R\x01d\"J\n" +
	"\x15OptionalStringMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x03tag\x18\x02 \x01(\tH\x00R\x03tag\x88\x01\x01B\x06\n" +
	"\x04_tag\"e\n" +
	"\x15OptionalStructMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x06server\x18\x02 \x01(\v2\x10.testdata.ServerH\x00R\x06server\x88\x01\x01B\t\n" +
	"\a_server*\"\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06active\x10\x00\x12\f\n" +
	"\binactive\x10\x01B\x16Z\x14comptime-serde/testsb\x06proto3"

var (
	file_testdata_proto_rawDescOnce sync.Once
	file_testdata_proto_rawDescData []byte
)

func file_testdata_proto_rawDescGZIP() []byte {
	file_testdata_proto_rawDescOnce.Do(func() {
		file_testdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_proto_rawDesc), len(file_testdata_proto_rawDesc)))
	})
	return file_testdata_proto_rawDescData
}

var file_testdata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testdata_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_testdata_proto_goTypes = []any{
	(Status)(0),                   // 0: testdata.Status
	(*SimpleMessage)(nil),         // 1: testdata.SimpleMessage
	(*Server)(nil),                // 2: testdata.Server
	(*NestedMessage)(nil),         // 3: testdata.NestedMessage
	(*PackedScalars)(nil),         // 4: testdata.PackedScalars
	(*RepeatedMessage)(nil),       // 5: testdata.RepeatedMessage
	(*EnumMessage)(nil),           // 6: testdata.EnumMessage
	(*SignedMessage)(nil),         // 7: testdata.SignedMessage
	(*FloatMessage)(nil),          // 8: testdata.FloatMessage
	(*OptionalStringMessage)(nil), // 9: testdata.OptionalStringMessage
	(*OptionalStructMessage)(nil), // 10: testdata.OptionalStructMessage
}
var file_testdata_proto_depIdxs = []int32{
	2, // 0: testdata.NestedMessage.server:type_name -> testdata.Server
	2, // 1: testdata.RepeatedMessage.servers:type_name -> testdata.Server
	0, // 2: testdata.EnumMessage.status:type_name -> testdata.Status
	2, // 3: testdata.OptionalStructMessage.server:type_name -> testdata.Server
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_testdata_proto_init() }
func file_testdata_proto_init() {
	if File_testdata_proto != nil {
		return
	}
	file_testdata_proto_msgTypes[8].OneofWrappers = []any{}
	file_testdata_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_proto_rawDesc), len(file_testdata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_proto_goTypes,
		DependencyIndexes: file_testdata_proto_depIdxs,
		EnumInfos:         file_testdata_proto_enumTypes,
		MessageInfos:      file_testdata_proto_msgTypes,
	}.Build()
	File_testdata_proto = out.File
	file_testdata_proto_goTypes = nil
	file_testdata_proto_depIdxs = nil
}
